### PR TITLE
Sensor api

### PR DESCRIPTION
**Pull request by Cyberzoid1**
Sensor api update to match https://github.com/uidaho/smartsettia/pull/82

Since the dashboard is not up-to-date. its hard to tell if sensor data is coming in correctly.
Although i am seeing some data in the tables.

### CODE REVIEW

**Review by brandonjank — COMMENTED** [review]
Doesn't seem to be working for me. I tested on fresh c9 on this branch. Here's what I got on stdout:
```
backburn:~/workspace (sensor-api) $ ./main.py -npi -fw
/home/ubuntu/workspace/cover.py:139: SyntaxWarning: name 'fsm_transition_state' is used prior to global declaration
  global fsm_transition_state
/home/ubuntu/workspace/cover.py:198: SyntaxWarning: name 'fsm_transition_state' is used prior to global declaration
  global fsm_transition_state

Welcome to Smartsettia!
uuid:  0c3ecb6d-2f88-57cb-b7ef-c39e42c8613e
Loading settings
        Load settings error  [Errno 2] No such file or directory: 'config.json'
Using fake webcam:  True
Not Pi flag set. GPIO is disabled.
Using domain https://smartsettia.com/
        URL register: https://smartsettia.com/api/register
        URL status:   https://smartsettia.com/api/update
        URL sensors:  https://smartsettia.com/api/update
        URL image:    https://smartsettia.com/api/image
Ramdisk does not exist. Using /tmp/

--- Registering Device ---------------
URL:   https://smartsettia.com/api/register
--- Registration return ---
Response code:  201
Token:  tEKyIhIlaA5sF33QWILuomhOHQV3Ad7ToPFodKGBfsBxPsP4wCQHRTovsd7P
Name:   New Device
ID:     85
Registration Successful
--------------------------------------
Cover monitor - Current state error
Reading limit switches
        ## Simulating switches
        Current sensors open/closed (1,0)
        Current server command:  close
Entered State: Error
fsm - Next state open
--------------------------------------
Cover monitor - Current state open
Reading limit switches
        ## Simulating switches
        Current sensors open/closed (1,0)
        Current server command:  close
Entered State: open
Server change event: closing
fsm - Next state closing
--------------------------------------
Cover monitor - Current state closing
Reading limit switches
        ## Simulating switches
        Current sensors open/closed (1,0)
        Current server command:  close
Entered State: closing  Substate: ts0:RelayOn
Setting Relay to on
not pi:  True
        GPIO disabled
        Relay -time is: 1508566131.3,    wait time: 1508566134.3
fsm - Next state closing
--------------------------------------

--- Uploading Status -----------------
Device ID: 85
        Cover status:  closing
        Error message: 'TEST ERROR'
remote_comm:status_update:Error sending request
         request() got an unexpected keyword argument 'json'
remote_comm:status_update:Error writing to log
local variable 'req' referenced before assignment
remote_comm:status_update:General Error
--------------------------------------
Cover monitor - Current state closing
Reading limit switches
        ## Simulating switches
        Current sensors open/closed (0,0)
        Current server command:  close
Entered State: closing  Substate: ts1:RelayWait
fsm - Next state closing
--------------------------------------

--- Getting picture ------------------
Img Filename:  /tmp/webcam_img.jpg
-1 / unknownfilename:  /tmp/webcam_img.jpg
timepic: 129
--- Uploading Picture ----------------
Image name:  /tmp/webcam_img.jpg
Response code:  201
Webcam upload Successful
--------------------------------------
Cover monitor - Current state closing
Reading limit switches
        ## Simulating switches
        Current sensors open/closed (0,0)
        Current server command:  close
Entered State: closing  Substate: ts1:RelayWait
fsm - Next state closing
--------------------------------------

--- Uploading Status -----------------
Device ID: 85
        Cover status:  closing
        Error message: 'TEST ERROR'
remote_comm:status_update:Error sending request
         request() got an unexpected keyword argument 'json'
remote_comm:status_update:Error writing to log
local variable 'req' referenced before assignment
remote_comm:status_update:General Error
--------------------------------------
Cover monitor - Current state closing
Reading limit switches
        ## Simulating switches
        Current sensors open/closed (0,0)
        Current server command:  close
Entered State: closing  Substate: ts1:RelayWait
Setting Relay to off
not pi:  True
        GPIO disabled
fsm - Next state closing
--------------------------------------
Getting Sensors..
Tempsensor [3]:  {'type': 'temperature', 'value': '51', 'name': 'temperature'}
Temp: 52        Cpu Temp: 87    Light: 15

--- Uploading Sensor Data-------------
https://smartsettia-nkrenowicz.c9users.io/api/sensor
json dmp:  {"sensor_data": [{"type": "cpu_temperature", "value": "0.00", "name": "cpu"}, {"type": "light", "value": "15", "name": "light_in"}, {"type": "light", "value": "15", "name": "light_out"}, {"type": "temperature", "value": "51", "name": "temperature"}, {"type": "humidity", "value": "86", "name": "humidity"}], "server_command": "close", "cover_status": "closing", "token": "tEKyIhIlaA5sF33QWILuomhOHQV3Ad7ToPFodKGBfsBxPsP4wCQHRTovsd7P", "error_msg": "TEST ERROR", "uuid": "0c3ecb6d-2f88-57cb-b7ef-c39e42c8613e"}
remote_comm:sensor_upload:Error sending request
         request() got an unexpected keyword argument 'json'
remote_comm:sensor_upload:Error writing to log
local variable 'req' referenced before assignment
remote_comm:sensor_upload:General Error
```

**Comment by brandonjank** [comment]
image

**Comment by Cyberzoid1** [comment]
Fixed sensor url.

Original pr was working until by using the old /api/update for the sensor url. This depreciated url was working until it was removed in a server update.

52858e2 fixed the url to use the new /api/sensor but created a new error in a print statement that was not updated to the new dictionary key. fixed in 27735cb

**Comment by brandonjank** [comment]
It looks like the script requires sudo to be run. There must be a way to get access to pi gpio data without root.
image

**Comment by brandonjank** [comment]
Getting multiple errors:
```
backburn:~/workspace (sensor-api) $ ./main.py -fw -npi

Welcome to Smartsettia!
uuid:  0c3ecb6d-2f88-57cb-b7ef-c39e42c8613e
Loading settings
        Load settings error  [Errno 2] No such file or directory: 'config.json'
Using fake webcam:  True
Not Pi flag set. GPIO is disabled.
Using domain https://smartsettia.com/
        URL register: https://smartsettia.com/api/register
        URL status:   https://smartsettia.com/api/update
        URL sensors:  https://smartsettia.com/api/sensor
        URL image:    https://smartsettia.com/api/image
Ramdisk does not exist. Using /tmp/

--- Registering Device ---------------
URL:   https://smartsettia.com/api/register
--- Registration return ---
Response code:  200
Token:  tEKyIhIlaA5sF33QWILuomhOHQV3Ad7ToPFodKGBfsBxPsP4wCQHRTovsd7P
Name:   New Device
ID:     85
Registration Successful
--------------------------------------
Cover monitor - Current state error
Reading limit switches
        ## Simulating switches
        Current sensors open/closed (1,0)
        Current server command:  close
Entered State: Error
fsm - Next state open
--------------------------------------
Cover monitor - Current state open
Reading limit switches
        ## Simulating switches
        Current sensors open/closed (1,0)
        Current server command:  close
Entered State: open
Server change event: closing
fsm - Next state closing
--------------------------------------
Cover monitor - Current state closing
Reading limit switches
        ## Simulating switches
        Current sensors open/closed (1,0)
        Current server command:  close
Entered State: closing  Substate: ts0:RelayOn
Setting Relay to on
not pi:  True
        GPIO disabled
        Relay -time is: 1508884678.7,    wait time: 1508884681.7
fsm - Next state closing
--------------------------------------

--- Uploading Status -----------------
Device ID: 85
        Cover status:  closing
        Error message: 'TEST ERROR'
remote_comm:status_update:Error sending request
         request() got an unexpected keyword argument 'json'
remote_comm:status_update:Error writing to log
local variable 'req' referenced before assignment
remote_comm:status_update:General Error
--------------------------------------
Cover monitor - Current state closing
Reading limit switches
        ## Simulating switches
        Current sensors open/closed (0,0)
        Current server command:  close
Entered State: closing  Substate: ts1:RelayWait
fsm - Next state closing
--------------------------------------

--- Getting picture ------------------
Img Filename:  /tmp/webcam_img.jpg
-1 / unknownfilename:  /tmp/webcam_img.jpg
timepic: 131
--- Uploading Picture ----------------
Image name:  /tmp/webcam_img.jpg
Response code:  201
Webcam upload Successful
--------------------------------------
Cover monitor - Current state closing
Reading limit switches
        ## Simulating switches
        Current sensors open/closed (0,0)
        Current server command:  close
Entered State: closing  Substate: ts1:RelayWait
fsm - Next state closing
--------------------------------------

--- Uploading Status -----------------
Device ID: 85
        Cover status:  closing
        Error message: 'TEST ERROR'
remote_comm:status_update:Error sending request
         request() got an unexpected keyword argument 'json'
remote_comm:status_update:Error writing to log
local variable 'req' referenced before assignment
remote_comm:status_update:General Error
--------------------------------------
Cover monitor - Current state closing
Reading limit switches
        ## Simulating switches
        Current sensors open/closed (0,0)
        Current server command:  close
Entered State: closing  Substate: ts1:RelayWait
Setting Relay to off
not pi:  True
        GPIO disabled
fsm - Next state closing
--------------------------------------
Getting Sensors..
Tempsensor [3]:  {'type': 'temperature', 'value': '51', 'name': 'temperature'}
Temp: 52        Cpu Temp: 87    Light: 15

--- Uploading Sensor Data-------------
https://smartsettia.com/api/sensor
json dmp:  {"server_command": "close", "error_msg": "TEST ERROR", "sensor_data": [{"type": "cpu_temperature", "value": "0.00", "name": "cpu"}, {"type": "light", "value": "15", "name": "light_in"}, {"type": "light", "value": "15", "name": "light_out"}, {"type": "temperature", "value": "51", "name": "temperature"}, {"type": "humidity", "value": "86", "name": "humidity"}], "uuid": "0c3ecb6d-2f88-57cb-b7ef-c39e42c8613e", "cover_status": "closing", "token": "tEKyIhIlaA5sF33QWILuomhOHQV3Ad7ToPFodKGBfsBxPsP4wCQHRTovsd7P"}
remote_comm:sensor_upload:Error sending request
         request() got an unexpected keyword argument 'json'
remote_comm:sensor_upload:Error writing to log
local variable 'req' referenced before assignment
remote_comm:sensor_upload:General Error
--------------------------------------
Cover monitor - Current state closing
Reading limit switches
        ## Simulating switches
        Current sensors open/closed (0,0)
        Current server command:  close
Entered State: closing  Substate: ts3:MovingTest
        Cover -time is: 1508884683.1,    timout time: 1508884708.1
fsm - Next state closing
--------------------------------------

--- Uploading Status -----------------
Device ID: 85
        Cover status:  closing
        Error message: 'TEST ERROR'
remote_comm:status_update:Error sending request
         request() got an unexpected keyword argument 'json'
remote_comm:status_update:Error writing to log
local variable 'req' referenced before assignment
remote_comm:status_update:General Error
--------------------------------------
```

**Comment by brandonjank** [comment]
Still has ```request() got an unexpected keyword argument 'json'``` error:

```
Welcome to Smartsettia!
Version: 0.2.1
uuid:  0c3ecb6d-2f88-57cb-b7ef-c39e42c8613e
Loading settings
        Load settings error  [Errno 2] No such file or directory: 'config.json'
Using fake webcam:  True
Not Pi flag set. GPIO is disabled.
Using domain https://smartsettia.com/
        URL register: https://smartsettia.com/api/register
        URL status:   https://smartsettia.com/api/update
        URL sensors:  https://smartsettia.com/api/sensor
        URL image:    https://smartsettia.com/api/image
Ramdisk does not exist. Using /tmp/

--- Registering Device ---------------
URL:   https://smartsettia.com/api/register
--- Registration return ---
Response code:  200
Token:  tEKyIhIlaA5sF33QWILuomhOHQV3Ad7ToPFodKGBfsBxPsP4wCQHRTovsd7P
Name:   New Device
ID:     85
Registration Successful
--------------------------------------
Cover monitor - Current state error
Reading limit switches
        ## Simulating switches
        Current sensors open/closed (1,0)
        Current server command:  close
Entered State: Error
fsm - Next state open
--------------------------------------
Cover monitor - Current state open
Reading limit switches
        ## Simulating switches
        Current sensors open/closed (1,0)
        Current server command:  close
Entered State: open
Server change event: closing
fsm - Next state closing
--------------------------------------
Cover monitor - Current state closing
Reading limit switches
        ## Simulating switches
        Current sensors open/closed (1,0)
        Current server command:  close
Entered State: closing  Substate: ts0:RelayOn
Setting Relay to on
not pi:  True
        GPIO disabled
        Relay -time is: 1508910549.0,    wait time: 1508910552.0
fsm - Next state closing
--------------------------------------

--- Uploading Status -----------------
Device ID: 85
        Cover status:  closing
        Error message: 'TEST ERROR'
remote_comm:status_update:Error sending request
         request() got an unexpected keyword argument 'json'
remote_comm:status_update:Error writing to log
local variable 'req' referenced before assignment
remote_comm:status_update:General Error
--------------------------------------
Cover monitor - Current state closing
Reading limit switches
        ## Simulating switches
        Current sensors open/closed (0,0)
        Current server command:  close
Entered State: closing  Substate: ts1:RelayWait
fsm - Next state closing
--------------------------------------

--- Getting picture ------------------
Img Filename:  /tmp/webcam_img.jpg
-1 / unknownfilename:  /tmp/webcam_img.jpg
timepic: 139
--- Uploading Picture ----------------
Image name:  /tmp/webcam_img.jpg
Response code:  201
Webcam upload Successful
--------------------------------------
Cover monitor - Current state closing
Reading limit switches
        ## Simulating switches
        Current sensors open/closed (0,0)
        Current server command:  close
Entered State: closing  Substate: ts1:RelayWait
fsm - Next state closing
--------------------------------------

--- Uploading Status -----------------
Device ID: 85
        Cover status:  closing
        Error message: 'TEST ERROR'
remote_comm:status_update:Error sending request
         request() got an unexpected keyword argument 'json'
remote_comm:status_update:Error writing to log
local variable 'req' referenced before assignment
remote_comm:status_update:General Error
--------------------------------------
Cover monitor - Current state closing
Reading limit switches
        ## Simulating switches
        Current sensors open/closed (0,0)
        Current server command:  close
Entered State: closing  Substate: ts1:RelayWait
Setting Relay to off
not pi:  True
        GPIO disabled
fsm - Next state closing
--------------------------------------
Getting Sensors..
Tempsensor [3]:  {'value': '51', 'type': 'temperature', 'name': 'temperature'}
Temp: 52        Cpu Temp: 87    Light: 15

--- Uploading Sensor Data-------------
https://smartsettia.com/api/sensor
json dmp:  {"token": "tEKyIhIlaA5sF33QWILuomhOHQV3Ad7ToPFodKGBfsBxPsP4wCQHRTovsd7P", "error_msg": "TEST ERROR", "uuid": "0c3ecb6d-2f88-57cb-b7ef-c39e42c8613e", "sensor_data": [{"value": "0.00", "type": "cpu_temperature", "name": "cpu"}, {"value": "15", "type": "light", "name": "light_in"}, {"value": "15", "type": "light", "name": "light_out"}, {"value": "51", "type": "temperature", "name": "temperature"}, {"value": "86", "type": "humidity", "name": "humidity"}], "server_command": "close", "cover_status": "closing"}
remote_comm:sensor_upload:Error sending request
         request() got an unexpected keyword argument 'json'
remote_comm:sensor_upload:Error writing to log
local variable 'req' referenced before assignment
remote_comm:sensor_upload:General Error
--------------------------------------
Cover monitor - Current state closing
Reading limit switches
        ## Simulating switches
        Current sensors open/closed (0,0)
        Current server command:  close
Entered State: closing  Substate: ts3:MovingTest
        Cover -time is: 1508910553.4,    timout time: 1508910578.4
fsm - Next state closing
--------------------------------------

--- Uploading Status -----------------
Device ID: 85
        Cover status:  closing
        Error message: 'TEST ERROR'
remote_comm:status_update:Error sending request
         request() got an unexpected keyword argument 'json'
remote_comm:status_update:Error writing to log
local variable 'req' referenced before assignment
remote_comm:status_update:General Error
--------------------------------------
```

**Comment by brandonjank** [comment]
Unrelated to the above error, it looks like you're sending other fields with the sensor update. The server just ignores them, so not a huge deal but they shouldn't be there: 
```
{"token": "tEKyIhIlaA5sF33QWILuomhOHQV3Ad7ToPFodKGBfsBxPsP4wCQHRTovsd7P", "error_msg": "TEST ERROR", "uuid": "0c3ecb6d-2f88-57cb-b7ef-c39e42c8613e", "sensor_data": [{"value": "0.00", "type": "cpu_temperature", "name": "cpu"}, {"value": "15", "type": "light", "name": "light_in"}, {"value": "15", "type": "light", "name": "light_out"}, {"value": "51", "type": "temperature", "name": "temperature"}, {"value": "86", "type": "humidity", "name": "humidity"}], "server_command": "close", "cover_status": "closing"}
```

Ideally it would just be:
```
{"token": "tEKyIhIlaA5sF33QWILuomhOHQV3Ad7ToPFodKGBfsBxPsP4wCQHRTovsd7P", "uuid": "0c3ecb6d-2f88-57cb-b7ef-c39e42c8613e", "sensor_data": [{"value": "0.00", "type": "cpu_temperature", "name": "cpu"}, {"value": "15", "type": "light", "name": "light_in"}, {"value": "15", "type": "light", "name": "light_out"}, {"value": "51", "type": "temperature", "name": "temperature"}, {"value": "86", "type": "humidity", "name": "humidity"}]}
```

**Pull request merged**
